name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: actions/checkout@v4
      uses: actions/checkout@v4

    - name: actions/setup-dotnet@v4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --no-restore --configuration Release
