name: Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - name: actions/checkout@v4
      uses: actions/checkout@v4

    - name: actions/setup-dotnet@v4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet publish
      run: dotnet publish DapperCodeGenerator.Web -c Release -o dist

    - name: actions/configure-pages@v4
      uses: actions/configure-pages@v4

    - name: actions/upload-pages-artifact@v3
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist/wwwroot

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: actions/deploy-pages@v4
      id: deployment
      uses: actions/deploy-pages@v4
